# Generated by Django 4.1.4 on 2023-01-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anleitung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anleittitel', models.CharField(max_length=100)),
                ('ersteller', models.CharField(max_length=100)),
                ('kategorie', models.CharField(max_length=100)),
                ('dauer', models.TimeField(auto_now_add=True)),
                ('datum', models.DateField(verbose_name='datum_erstellt')),
            ],
        ),
    ]
