# Generated by Django 4.1.4 on 2023-01-07 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SBSInstruktionApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anleitungsschritt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schrittbenennung', models.CharField(max_length=50)),
                ('beschreibung', models.CharField(max_length=500)),
                ('schrittbild', models.ImageField(upload_to='images/Schrittbilder')),
            ],
        ),
        migrations.AddField(
            model_name='anleitung',
            name='thumbnailbild',
            field=models.ImageField(default=0, upload_to='images/Anleitungsbilder'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Komponenten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kompbeschreibung', models.CharField(max_length=100)),
                ('kompbild', models.ImageField(upload_to='images/Komponentenbilder')),
                ('anleitungsschritt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SBSInstruktionApp.anleitungsschritt')),
            ],
        ),
        migrations.AddField(
            model_name='anleitungsschritt',
            name='anleitung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SBSInstruktionApp.anleitung'),
        ),
    ]
