# Generated by Django 3.2.12 on 2023-01-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBSInstruktionApp', '0002_anleitungsschritt_anleitung_thumbnailbild_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anleitung',
            name='thumbnailbild',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='anleitungsschritt',
            name='schrittbild',
            field=models.ImageField(default=None, upload_to='images/Schrittbilder/'),
        ),
        migrations.AlterField(
            model_name='komponenten',
            name='kompbild',
            field=models.ImageField(default=None, upload_to='images/Kompbilder'),
        ),
    ]
