# Generated by Django 3.2.12 on 2023-01-22 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SBSInstruktionApp', '0003_auto_20230122_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anleitung',
            name='thumbnailbild',
        ),
        migrations.RemoveField(
            model_name='anleitungsschritt',
            name='schrittbild',
        ),
        migrations.RemoveField(
            model_name='komponenten',
            name='kompbild',
        ),
    ]
