# Generated by Django 3.2.12 on 2023-03-22 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SBSInstruktionApp', '0004_auto_20230122_1621'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Komponenten',
            new_name='Komponente',
        ),
        migrations.AlterField(
            model_name='anleitungsschritt',
            name='anleitung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anleitungsbezeichnungen', to='SBSInstruktionApp.anleitung'),
        ),
    ]
